kernel:
  image: linuxkit/kernel:4.19.99
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:a4fcf333298f644dfac6adf680b83140927aa85e
  - linuxkit/runc:69b4a35eaa22eba4990ee52cccc8f48f6c08ed03
  - linuxkit/containerd:09553963ed9da626c25cf8acdf6d62ec37645412
onboot:
  - name: vrouter
    image: kmod-test
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
    capabilities:
     - all
#  - name: dhcpcd
#    image: dhcpd-vhost
#    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
