/*
* Autogenerated file. DO NOT EDIT.
*/

const char *ContrailBuildInfo = "{\"build-info\": [{\"build-time\": \"2020-02-20 00:35:47.073918\", \"build-hostname\": \"d3b07bc07165\", \"build-user\": \"root\", \"build-version\": \"2003\"}]}";
